// <auto-generated />
using System;
using DadosPublicosCnpj.Data.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DadosPublicosCnpj.Data.Migrations
{
    [DbContext(typeof(EFContexto))]
    partial class EFContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DadosPublicosCnpj.Data.Modelos.Cnae", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CnaeSecundaria")
                        .HasColumnType("bigint");

                    b.Property<string>("Cnpj")
                        .HasColumnType("nvarchar(14)")
                        .HasMaxLength(14);

                    b.HasKey("Id");

                    b.ToTable("Cnaes");
                });

            modelBuilder.Entity("DadosPublicosCnpj.Data.Modelos.Empresa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bairro")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("CEP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CapitalSocial")
                        .HasColumnType("bigint");

                    b.Property<int>("CnaeFiscal")
                        .HasColumnType("int");

                    b.Property<string>("Cnpj")
                        .HasColumnType("nvarchar(14)")
                        .HasMaxLength(14);

                    b.Property<int>("CodigoMunicipio")
                        .HasColumnType("int");

                    b.Property<int>("CodigoNaturezaJuridica")
                        .HasColumnType("int");

                    b.Property<string>("CodigoPais")
                        .HasColumnType("nvarchar(3)")
                        .HasMaxLength(3);

                    b.Property<string>("Complemento")
                        .HasColumnType("nvarchar(156)")
                        .HasMaxLength(156);

                    b.Property<DateTime?>("DataExclusaoSimples")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataInicioAtividade")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataOpcaoSimples")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataSituacaoCadastral")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataSituacaoEspecial")
                        .HasColumnType("datetime2");

                    b.Property<string>("DddTelefone1")
                        .HasColumnType("nvarchar(4)")
                        .HasMaxLength(4);

                    b.Property<string>("DddTelefone2")
                        .HasColumnType("nvarchar(4)")
                        .HasMaxLength(4);

                    b.Property<string>("DescricaoTipoLogradouro")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(115)")
                        .HasMaxLength(115);

                    b.Property<int>("IdentificadorEmpresa")
                        .HasColumnType("int");

                    b.Property<string>("Logradouro")
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.Property<int>("MotivoSituacaoCadastral")
                        .HasColumnType("int");

                    b.Property<string>("Municipio")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("NomeCidadeExterior")
                        .HasColumnType("nvarchar(55)")
                        .HasMaxLength(55);

                    b.Property<string>("NomeFantasia")
                        .HasColumnType("nvarchar(55)")
                        .HasMaxLength(55);

                    b.Property<string>("NomePais")
                        .HasColumnType("nvarchar(70)")
                        .HasMaxLength(70);

                    b.Property<string>("Numero")
                        .HasColumnType("nvarchar(6)")
                        .HasMaxLength(6);

                    b.Property<bool>("OpcaoPeloMEI")
                        .HasColumnType("bit");

                    b.Property<int>("OpcaoSimples")
                        .HasColumnType("int");

                    b.Property<int>("PorteEmpresa")
                        .HasColumnType("int");

                    b.Property<int>("QualificacaoResponsavel")
                        .HasColumnType("int");

                    b.Property<string>("RazaoSocial")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<int>("SistuacaoCadastral")
                        .HasColumnType("int");

                    b.Property<string>("SituacaoEspecial")
                        .HasColumnType("nvarchar(23)")
                        .HasMaxLength(23);

                    b.Property<string>("Telefone1")
                        .HasColumnType("nvarchar(8)")
                        .HasMaxLength(8);

                    b.Property<string>("Telefone2")
                        .HasColumnType("nvarchar(8)")
                        .HasMaxLength(8);

                    b.Property<string>("UF")
                        .HasColumnType("nvarchar(2)")
                        .HasMaxLength(2);

                    b.HasKey("Id");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("DadosPublicosCnpj.Data.Modelos.Socio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CapitalSocial")
                        .HasColumnType("int");

                    b.Property<string>("CnpjEmpresa")
                        .HasColumnType("nvarchar(14)")
                        .HasMaxLength(14);

                    b.Property<string>("CodigoPais")
                        .HasColumnType("nvarchar(3)")
                        .HasMaxLength(3);

                    b.Property<string>("CodigoQualificacaoRepresentanteLegal")
                        .HasColumnType("nvarchar(2)")
                        .HasMaxLength(2);

                    b.Property<string>("CpfCnpj")
                        .HasColumnType("nvarchar(14)")
                        .HasMaxLength(14);

                    b.Property<string>("CpfRepresentanteLegal")
                        .HasColumnType("nvarchar(11)")
                        .HasMaxLength(11);

                    b.Property<DateTime?>("DataEntrada")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdentificadorSocio")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("NomePais")
                        .HasColumnType("nvarchar(70)")
                        .HasMaxLength(70);

                    b.Property<string>("NomeRepresentanteLegal")
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.Property<string>("Qualificacao")
                        .HasColumnType("nvarchar(2)")
                        .HasMaxLength(2);

                    b.HasKey("Id");

                    b.ToTable("Socios");
                });
#pragma warning restore 612, 618
        }
    }
}
